### ISSUE TITLE
Reproducibility of designs from old versions

### ISSUE THREAD

**Issue by ugroempi** [bertcarnell/lhs#19] opened 2019-05-03 12:07 UTC
Hi Rob,

good to see that there seems to be a lot of progress on your package. 

I am not sure whether you are aware of the substantial change to random number generation with function `sample` with R version 3.6.0; I was made aware of this change, because this change caused a change in the test results of several of my packages:

> The default method for generating from a discrete uniform distribution (used in `sample()`, for instance) has been changed. This addresses the fact, pointed out by Ottoboni and Stark, that the previous method made `sample()` noticeably non-uniform on large populations. See PR#17494 for a discussion. The previous method can be requested using `RNGkind()` or `RNGversion()` if necessary for reproduction of old results. Thanks to Duncan Murdoch for contributing the patch and Gabe Becker for further assistance.
> 
> The output of `RNGkind()` has been changed to also return the ‘kind’ used by `sample()`.

While working on adjusting the documentation of my packages to reflect the new behavior of function `sample` in R 3.6.0 (i.e., telling users of all relevant functions to set the integer uniform random number generator to the old behavior (`RNGkind(sample.kind="Rounding")`), if needed for reproducing old designs, I discovered that I cannot make lhs results (in my package DoE.wrapper) reproducible in that way. It seems that the new version of your package consistently produces a different design from what the old version (I tried 0.13 and 0.14) would have produced under the same seed.

I observed this for 
`set.seed(1212)`
`maximinLHS(6,2)`

Is that intentional / known to you? Do you plan to keep future behavior consistent again?
I am asking because I want to provide the adequate information with the documentation of my function `lhs.design` in package DoE.wrapper.

Best, Ulrike

**Comment by bertcarnell** [comment] 2019-05-05 00:56
Ulrike,

It's good to hear from you.  You might have noticed that I added an orthogonal LHS to the package in this latest round.  It's something you and I discussed many years ago.  I'm certainly open to feedback if you have it.

I was aware of the random number generation changes, but thank you for the reminder anyway.  I have had other developers ask me about the reproducibility of the lhs code in the past.  Because I made a large number of changes, I'm reluctant to make random number reproducibility promises yet.  If users need reproducibility for testing today, I suggest they save the design.

I feel like the maximinLHS algorithm is the weakest algorithm in my package.  In particular, I think that it doesn't perform with the guarantee that most people expect from it.  For example, I can't claim that maximinLHS(6,2) actually produces the uniformly best sample that maximizes the minimum distance.  The first algorithm I wrote builds an lhs one point at a time, adding the best next point to the design among a group of candidates.  The algorithm does not guarantee maximin.  In my latest package iteration, I've added other algorithms to maximinLHS to get closer to maximin if users want to spend the computation time.  I expect to move that code from R to C++ in my next improvement.  Moving to C++ makes it hard to guarantee the same random draws again.

When I released this last version, I made sure to perform the reverse dependency checks for your packages, but I didn't notice any problems.  I hope I didn't cause trouble for DOE.wrapper.

Rob

**Comment by ugroempi** [comment] 2019-05-05 12:57
Thanks, Rob! So I take it that using a seed gives the same result short term under the same package version (and RNG setting), but consistency between package versions cannot be expected for the time being. Is that correct? Then I'll document this in DoE.wrapper. 

Your changes didn't give trouble for my packages, only the change in RNG did ...

I like your new oa_to_oalhs functionality, and it has given me some ideas regarding the use of regular or non-regular arrays. I'll e-mail you about those outside of github.

Best, Ulrike

**Comment by bertcarnell** [comment] 2019-05-20 18:31
Yes.  Consistency between versions cannot yet be guaranteed.  MaximinLHS is the one function most in danger of change.  randomLHS will likely be stable.

**Closed** 2020-03-26 18:53 UTC
Labels: question
